// src/utils/action-types.js
// contact reducer
export const SEARCH_CONTACT = 'SEARCH_CONTACT';
export const GET_ALL_CONTACT_NAME = 'GET_ALL_CONTACT_NAME';
export const GET_ALL_PROGRAM_INFO = 'GET_ALL_PROGRAM_INFO';
export const SAVE_EDITED_CONTACT = 'SAVE_EDITED_CONTACT';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const MAYBE_UPDATE_SUGGESTIONS = 'MAYBE_UPDATE_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const ERASE_SEARCH_VALUE = 'ERASE_SEARCH_VALUE';
export const ON_LOCK_EDITON = 'ON_LOCK_EDITON';
export const CONTACT_SAVED = 'CONTACT_SAVED';
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';
export const ADD_NEW_SUPPLIER = 'ADD_NEW_SUPPLIER';
export const SET_CONTACT_TO_DELETE = 'SET_CONTACT_TO_DELETE';
export const HANDLE_MOVE_CANCEL = 'HANDLE_MOVE_CANCEL';
export const HANDLE_ERROR_OPEN = 'HANDLE_ERROR_OPEN';
export const HANDLE_ERROR_CLOSE = 'HANDLE_ERROR_CLOSE';
export const RESET_CONTACT_TO_DELETE = 'RESET_CONTACT_TO_DELETE';
export const DELETE_CONTACT_FROM_RESULTS = 'DELETE_CONTACT_FROM_RESULTS';
export const CANCEL_NEW_CONTACT = 'CANCEL_NEW_CONTACT';
export const ON_VALIDATE_PROGRAM_SELECTION = 'ON_VALIDATE_PROGRAM_SELECTION';
export const GET_SIDE_MENU = 'GET_SIDE_MENU';
// program reducer
export const SET_PRODUCTOR_LIST = 'SET_PRODUCTOR_LIST';
export const SET_PROGRAM_LIST = 'SET_PROGRAM_LIST';
export const SET_VERSION_LIST = 'SET_VERSION_LIST';
export const PRODUCTOR_SELECTED = 'PRODUCTOR_SELECTED';
export const PROGRAM_SELECTED = 'PROGRAM_SELECTED';
export const VERSION_SELECTED = 'VERSION_SELECTED';
export const SAVE_NEW_PRODUCTOR = 'SAVE_NEW_PRODUCTOR';
export const SAVE_NEW_PROGRAM = 'SAVE_NEW_PROGRAM';
export const SAVE_NEW_VERSION = 'SAVE_NEW_VERSION';
export const OPEN_ALERT_BOX = 'OPEN_ALERT_BOX';
export const ON_VALIDATE_PROGRAM = 'ON_VALIDATE_PROGRAM';
